/** All Products mega-menu trees matching FS.com (New/Hot badges). */
export const L = (label, badge) => ({ label, badge });

export const MEGA = {
  switches: [
    { name: "PicOS® Enterprise Switches", img: "/images/20250116162633cququm.png", href: "/c/switches", links: [L("1/2.5G PicOS® Switches", "Hot"), L("10/25G PicOS® Switches"), L("40/100G PicOS® Switches", "New"), L("200/400G PicOS® Switches", "New"), L("AmpCon-Campus Platform")] },
    { name: "PicOS® Data Center Switches", img: "/images/20250116162705er3rbv.png", href: "/c/switches", links: [L("10/25G PicOS® Switches"), L("100/200G PicOS® Switches", "Hot"), L("400/800G PicOS® Switches", "Hot"), L("HPC/AI PicOS® Switches", "New"), L("PicOS® NPB")] },
    { name: "PicOS® PoE+ Switches", img: "/images/20250712105444jwgqkj.png", href: "/c/switches", links: [L("1G PicOS® PoE+ Switches"), L("2.5/5G PicOS® PoE+ Switches", "Hot"), L("10G PicOS® PoE+ Switches", "New"), L("AmpCon-Campus Platform"), L("PicOS® License & Service")] },
    { name: "Industrial Ethernet Switches", img: "/images/20230508182555_651.png", href: "/c/switches", links: [L("DIN Rail Mount Industrial"), L("Rack Mount Industrial"), L("Wall Mount Industrial"), L("TSN Industrial Switches", "New"), L("Industrial PoE+ Switches", "Hot")] },
    { name: "Enterprise Switches", img: "/images/20250116162126hja9wv.png", href: "/c/switches", links: [L("1/2.5G Enterprise Switches", "Hot"), L("10G Enterprise Switches"), L("25G Enterprise Switches"), L("40G Enterprise Switches"), L("100G Enterprise Switches")] },
    { name: "Data Center Switches", img: "/images/202501161625092pt2sj.png", href: "/c/switches", links: [L("10/25G Data Center Switches"), L("100G Data Center Switches", "Hot"), L("Modular Data Center Switches"), L("Network Packet Brokers"), L("NVIDIA® Switches", "New")] },
    { name: "PoE+ Switches", img: "/images/20230512103812_200.png", href: "/c/switches", links: [L("1G PoE+ Switches", "Hot"), L("2.5/5G PoE+ Switches"), L("10G PoE++ Switches"), L("Switch Accessories")] },
    { name: "SME Switches", img: "/images/20260223142838c3xw17.png", href: "/c/switches", links: [L("Compact SME Switches"), L("Standard SME Switches", "Hot"), L("Professional SME Switches"), L("Professional Max SME"), L("Aggregation SME Switches")] },
  ],
  networking: [
    { name: "Wireless", img: "/images/20251014172228tp621m.png", href: "/c/networking", links: [L("Wi-Fi 7 Access Points", "New"), L("Wi-Fi 6 Access Points", "Hot"), L("Wi-Fi 5 Access Points"), L("Wireless Controllers"), L("Wi-Fi Routers")] },
    { name: "Cameras & Surveillance", img: "/images/20250712105444jwgqkj.png", href: "/c/networking", links: [L("IP Cameras", "Hot"), L("PoE Cameras"), L("Outdoor Cameras"), L("NVR / VMS")] },
    { name: "Conferencing, Phones", img: "/images/20250116162126hja9wv.png", href: "/c/networking", links: [L("IP Phones"), L("Conference Phones"), L("Video Endpoints")] },
    { name: "Media Converters", img: "/images/20220409112509_426.png", href: "/c/networking", links: [L("Fiber to Ethernet", "Hot"), L("PoE Media Converters"), L("Industrial Converters")] },
    { name: "Network Adapters", img: "/images/20230321165822_776.png", href: "/c/networking", links: [L("PCIe NICs"), L("10G/25G NICs", "Hot"), L("100G NICs", "New"), L("SmartNICs")] },
    { name: "Servers & KVM", img: "/images/202501161625092pt2sj.png", href: "/c/networking", links: [L("1U/2U Servers"), L("KVM Switches"), L("Server Accessories")] },
    { name: "Router, Security, NPB", img: "/images/20250116162705er3rbv.png", href: "/c/networking", links: [L("Enterprise Routers"), L("Firewalls"), L("Network Packet Brokers", "New")] },
    { name: "Power", img: "/images/20220524152815_811.jpg", href: "/c/networking", links: [L("PDU", "Hot"), L("UPS"), L("Power Cords")] },
  ],
  transceivers: [
    { name: "AI InfiniBand Modules", img: "/images/2026052514533153hnfm.png", href: "/c/transceivers", links: [L("InfiniBand 1.6T/800G XDR", "New"), L("InfiniBand 800G/400G NDR", "Hot"), L("InfiniBand 400G/200G HDR"), L("InfiniBand 100G EDR"), L("Transceivers & Cables Custom")] },
    { name: "AI Ethernet Modules", img: "/images/20220409111938_554.png", href: "/c/transceivers", links: [L("1.6T OSFP224", "New"), L("800G/400G OSFP/QSFP112", "Hot"), L("400G/200G QSFP-DD/QSFP56", "Hot"), L("100G QSFP28", "Hot"), L("Transceivers & Cables Custom")] },
    { name: "800/400/200/100G Modules", img: "/images/20220409111613_260.png", href: "/c/transceivers", links: [L("800G OSFP/QSFP-DD", "Hot"), L("400G OSFP/QSFP112/QSFP-DD", "Hot"), L("200G QSFP-DD/QSFP56", "Hot"), L("100G QSFP28", "Hot"), L("40G QSFP+"), L("Transceivers Custom")] },
    { name: "50/25/10/1G Modules", img: "/images/20220409112509_426.png", href: "/c/transceivers", links: [L("50G QSFP28/SFP56"), L("25G SFP28"), L("10G SFP+", "Hot"), L("2.5G SFP"), L("1G SFP", "Hot"), L("100M SFP"), L("Transceivers Custom")] },
    { name: "Optical Transmission", img: "/images/20230130182452_449.png", href: "/c/transceivers", links: [L("800G/400G Coherent OSFP/…", "New"), L("800G/400G/200G Coherent CFP2"), L("100G DWDM QSFP28"), L("100G CFP/CFP2/CFP4"), L("25G CWDM/DWDM SFP28"), L("10G CWDM/DWDM SFP+", "Hot"), L("1G CWDM/DWDM SFP"), L("Transceivers Custom")] },
    { name: "Mobile & Access Network", img: "/images/2025102915514707tvtk.jpg", href: "/c/transceivers", links: [L("Industrial Transceivers", "Hot"), L("GPON & XGSPON Sticks", "Hot"), L("GPON, XG(S)PON, Combo"), L("EPON, 10G EPON"), L("50G SFP56 for 5G Wireless"), L("25G SFP28 for 5G Wireless"), L("10G SFP+ for 4G Wireless"), L("Transceivers Custom")] },
    { name: "DAC/AOC/ACC/AEC Cables", img: "/images/20230321165822_776.png", href: "/c/transceivers", links: [L("1.6T/800G DAC/AOC/AEC", "New"), L("400G DAC/AOC/AEC", "New"), L("200G DAC/AOC"), L("100G DAC/AOC", "Hot"), L("56G/50G DAC/AOC"), L("40G DAC/AOC"), L("25G/10G/1G DAC/AOC", "Hot"), L("DAC/AOC/ACC/AEC Custom")] },
    { name: "Others", img: "/images/2026070311032715a10j.jpg", href: "/c/transceivers", links: [L("FS BOX", "Hot"), L("SDI Modules", "Hot"), L("Fibre Channel Modules"), L("Converter Modules"), L("Loopback Modules"), L("SONET/SDH Modules"), L("XFP/X2 Modules"), L("Accessories")] },
  ],
  cables: [
    { name: "MTP®/MPO Fiber Cables", img: "/images/12285.main.jpg", href: "/c/cables", links: [L("MTP® Trunk Cables", "Hot"), L("MTP® Breakout Cables"), L("16/32 Fiber MTP®", "New"), L("Polarity Type A/B/C"), L("Custom MTP® Cables")] },
    { name: "Fiber Patch Cables", img: "/images/12285.main.jpg", href: "/c/cables", links: [L("OS2 Simplex/Duplex", "Hot"), L("OM4/OM5 Duplex", "Hot"), L("OM3 Duplex"), L("Uniboot LC"), L("Custom Length")] },
    { name: "MMC Fiber Connectivity", img: "/images/35488.main.jpg", href: "/c/cables", links: [L("MMC Jumpers", "New"), L("Very Small Form Factor"), L("High-Density MMC")] },
    { name: "Specialty Fiber Cables", img: "/images/12285.main.jpg", href: "/c/cables", links: [L("Armored Cables", "Hot"), L("Outdoor / Industrial"), L("Bend Insensitive"), L("Hybrid Power+Fiber")] },
    { name: "Fiber Pigtails", img: "/images/12285.main.jpg", href: "/c/cables", links: [L("LC/SC/FC/ST Pigtails", "Hot"), L("Ribbon Pigtails"), L("Color Coded 12F")] },
    { name: "Fiber Optic Connectivity", img: "/images/20260625112920j0ryma.jpg", href: "/c/cables", links: [L("Adapters", "Hot"), L("Connectors"), L("Attenuators"), L("Couplers")] },
    { name: "Cleaners & Tools", img: "/images/39721.1619489384125.jpg", href: "/c/cables", links: [L("One-Push Pens", "Hot"), L("Cleaning Cassettes"), L("Wipes & Sticks")] },
    { name: "Splitters & Closures", img: "/images/20260604162517vxm3jd.jpg", href: "/c/cables", links: [L("PLC Splitters", "Hot"), L("FBT Splitters"), L("Fiber Closures")] },
  ],
  panels: [
    { name: "Fiber Optic Panels", img: "/images/35488.main.jpg", href: "/c/panels", links: [L("FHD® Adapter Panels", "Hot"), L("LGX Panels"), L("1U/2U/4U Panels")] },
    { name: "Fiber Cassettes", img: "/images/20260624115840f1ugfm.jpg", href: "/c/panels", links: [L("FHD® Cassettes", "Hot"), L("MTP-LC Cassettes", "New"), L("Splice Cassettes")] },
    { name: "Fiber Enclosures", img: "/images/20251031104722830g5b.webp", href: "/c/panels", links: [L("FHD® Enclosures", "Hot"), L("Wall Mount Enclosures"), L("Rack Mount Enclosures")] },
    { name: "Cable Management", img: "/images/202608251816347hysti.webp", href: "/c/panels", links: [L("Horizontal Managers"), L("Vertical Managers"), L("D-Rings")] },
    { name: "Power", img: "/images/20220524152815_811.jpg", href: "/c/panels", links: [L("PDU", "Hot"), L("Power Cords"), L("ATS")] },
    { name: "Racks & Cabinets", img: "/images/202501161625092pt2sj.png", href: "/c/panels", links: [L("42U Cabinets"), L("Open Frames"), L("Wall Cabinets")] },
    { name: "Labels & Printers", img: "/images/202606282138103xhx5c.jpg", href: "/c/panels", links: [L("Cable Labels"), L("Label Printers")] },
  ],
  optical: [
    { name: "Optical DCI Network", img: "/images/20250421112225_320.jpg.webp", href: "/c/optical", links: [L("D7000 Series", "New"), L("400G DCI", "Hot"), L("Coherent Transport")] },
    { name: "Optical Line System", img: "/images/20260618153751r4eszs.jpg", href: "/c/optical", links: [L("M6200 Series", "Hot"), L("FMT Series"), L("EDFA"), L("DCM")] },
    { name: "Enterprise Integrated System", img: "/images/20251113174249s74e2v.jpg", href: "/c/optical", links: [L("All-in-one OTN", "New"), L("Campus WDM")] },
    { name: "Multiplexer & OADM", img: "/images/20260618153751r4eszs.jpg", href: "/c/optical", links: [L("CWDM Mux/Demux", "Hot"), L("DWDM Mux/Demux"), L("OADM")] },
    { name: "PON Network", img: "/images/20260604162517vxm3jd.jpg", href: "/c/optical", links: [L("OLT"), L("ONT"), L("PON Splitters", "Hot")] },
    { name: "Optical Distribution Network", img: "/images/35488.main.jpg", href: "/c/optical", links: [L("ODF"), L("ODB"), L("FDB")] },
    { name: "Optical Transmission", img: "/images/20230130182452_449.png", href: "/c/optical", links: [L("Transponders"), L("Muxponders", "New")] },
  ],
  copper: [
    { name: "Copper Patch Cords", img: "/images/71879.main.jpg", href: "/c/copper", links: [L("Cat6 Patch Cords", "Hot"), L("Cat6a Patch Cords", "Hot"), L("Cat8 Patch Cords", "New"), L("Slim / Snagless")] },
    { name: "Pre-Term Copper Trunks", img: "/images/71879.main.jpg", href: "/c/copper", links: [L("6/12/24 Port Trunks"), L("Shielded Trunks")] },
    { name: "Copper Bulk Cables", img: "/images/71879.main.jpg", href: "/c/copper", links: [L("Cat6 UTP", "Hot"), L("Cat6a STP"), L("Plenum / Riser")] },
    { name: "Copper Patch Panels", img: "/images/202606282138103xhx5c.jpg", href: "/c/copper", links: [L("24/48 Port Panels", "Hot"), L("Cat6a Panels"), L("Shielded Panels")] },
    { name: "Cable Management", img: "/images/202608251816347hysti.webp", href: "/c/copper", links: [L("Managers"), L("Velcro"), L("Rings")] },
    { name: "Faceplates & Boxes", img: "/images/202606282138103xhx5c.jpg", href: "/c/copper", links: [L("Wall Plates"), L("Surface Boxes")] },
    { name: "Connectors & Jacks", img: "/images/71879.main.jpg", href: "/c/copper", links: [L("Keystone Jacks", "Hot"), L("RJ45 Plugs")] },
    { name: "Copper Testers & Tools", img: "/images/20220607112907_607.png", href: "/c/copper", links: [L("Certifiers"), L("Punch Down Tools")] },
  ],
  tools: [
    { name: "Fiber Optic Testers", img: "/images/20220409095221_859.png", href: "/c/tools", links: [L("OTDR", "Hot"), L("Fiber Inspection"), L("Power Meters"), L("Fault Locators"), L("Light Sources")] },
    { name: "Fiber Optic Tools", img: "/images/20220409100241_777.png", href: "/c/tools", links: [L("Fiber Tool Kits"), L("Fiber Cleavers", "Hot"), L("Fiber Polishing"), L("Fiber Strippers"), L("Fiber Splicers")] },
    { name: "Fiber Optic Cleaners", img: "/images/20220409094902_665.png", href: "/c/tools", links: [L("Pen Cleaners", "Hot"), L("Sticks & Wipes"), L("Reel Type Cleaners")] },
    { name: "Copper Tools", img: "/images/20220607112827_839.png", href: "/c/tools", links: [L("Punch Down Tools"), L("Cable Strippers"), L("Network Tools")] },
    { name: "Copper Testers", img: "/images/20220607112907_607.png", href: "/c/tools", links: [L("Cable Certifiers", "Hot"), L("Tone & Probe"), L("PoE Testers")] },
  ],
};

export const NAV_MENUS = {
  solutions: [
    { label: "Data Center / AI Fabrics", href: "/solutions" },
    { label: "800G RoCE Lossless Network", href: "/solutions" },
    { label: "EVPN-VXLAN Fabric", href: "/solutions" },
    { label: "Enterprise Campus / Wi-Fi 7", href: "/solutions" },
    { label: "400G DCI / OTN", href: "/solutions" },
    { label: "FHD® Modular Cabling", href: "/solutions" },
  ],
  services: [
    { label: "Solution Consulting", href: "/contact" },
    { label: "Network Design", href: "/contact" },
    { label: "Compatibility Testing", href: "/support" },
    { label: "Custom Optics / Coding", href: "/contact" },
    { label: "PicOS® Feature Request", href: "/software" },
    { label: "Global Warehouse & Delivery", href: "/about" },
  ],
  resources: [
    { label: "Help Center", href: "/support" },
    { label: "Download Center", href: "/support" },
    { label: "Case Studies", href: "/about" },
    { label: "PicOS® / AmpCon Docs", href: "/software" },
    { label: "Blog & Insights", href: "/about" },
    { label: "Warranty / RMA", href: "/support" },
  ],
};
